print("Welcome to Haiku Generator")
print("Provide the first line of your haiku")
haiku = raw_input()
print("Provide the second line of your haiku")
line = raw_input()
print("provide the third line of your haiku")
lines = raw_input()
print("what file would you like to print your haiku into?")
file = raw_input()

myFile = open(file, "w")
myFile.write(haiku +"\n")
myFile.write(line + "\n")
myFile.write(lines + "\n")
myFile.close()
print("Done! To view your haiku, type 'cat' and the name of your file at the command line.")
