print("How much does it cost you for a coke?")
cost = raw_input()
print("How many cokes will you drink today?")
cokes = raw_input()
x = int(cost) * int(cokes)
print("Wow, you're going to spend " + str(x) + " dollars on suger water today!")
